<?php
	$traductions = ['fr'=>["nav1" => "A propos de moi",
					"nav2" => "Formations",
					"nav3" => "Experiences professionnelles",
					"nav4" => "Portfolio",
					"nav5" => "Contactez-moi",
					"prenom" => "Prénom :",
					"nom" => "Nom :",
					"dateNaissance" => "Date de naissance :",
					"tel" => "Téléphone :",
					"mail" => "Emai :",
					"apropos" => "A propos de moi :",
					"competences" => "Compétences :",
					"au" => "au",
					"inputName" => "Votre Nom",
					"inputMail" => "Votre Email",
					"inputSubject" => "Sujet",
					"inputSubmit" => "Envoyer",
					"inputReset" => "Réinitialiser",
					"erreurName" =>"Votre nom est invalide ou laissé vide",
					"erreurMail" =>"Adresse mail invalide ou laissé vide",
					"erreurSubject" =>"Votre sujet est invalide ou laissé vide",
					"erreurMessage" =>"Veuillez écrire votre message",
					"success" => "Votre message à bien été envoyé !",
					"jeSuis" => "Je suis Brahim LAMJARAD",
					"droit1" => "Tous Droits Réservés",
					"droit2" => "Conçu par"],
					'en'=>["nav1" => "About me",
					"nav2" => "Studies",
					"nav3" => "Experiences",
					"nav4" => "Portfolio",
					"nav5" => "Contact me",
					"prenom" => "First Name :",
					"nom" => "Last Name :",
					"dateNaissance" => "Date of Birth :",
					"tel" => "Phone :",
					"mail" => "Emai :",
					"au" => "to",
					"apropos" => "About me :",
					"competences" => "Skills :",
					"inputName" => "Your Name",
					"inputMail" => "Your Email",
					"inputSubject" => "Subject",
					"inputSubmit" => "Send",
					"inputReset" => "Reset",
					"erreurName" =>"Your name is invalid or leave blank",
					"erreurMail" =>"Email address invalid or leave blank",
					"erreurSubject" =>"Your subject is invalid or leave blank ",
					"erreurMessage" =>"Please write your message",
					"success" => "Your message has been sent !",
					"jeSuis" => "I am Lamjarad Brahim",
					"droit1" => "All Rights Reserved",
					"droit2" => "Designed by"]];

 ?>
